### ISSUE TITLE
Support link

### ISSUE THREAD

**Issue by mattwojo** [MicrosoftDocs/SamplesPages#109]
I see the question of support was raised in this vNext summary. I both just wanted to test this new comment system and promote adding a general support link to https://support.microsoft.com... it would be perfect to replace the blog announcement link and instead read "Our new feedback system is built on GitHub Issues. If you are looking for support, rather than to give product or documentation feedback, please visit https://support.microsoft.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f669346a-ec37-93ae-61b8-737c08751138
* Version Independent ID: 57ba8c4c-8836-0978-bdaa-565c8a4aec15
* [Content](https://review.docs.microsoft.com/en-us/new-hope/specs/community-engagement/feedback-vnext?branch=master)
* [Content Source](https://github.com/MicrosoftDocs/new-hope/blob/master/new-hope/specs/community-engagement/feedback-vnext.md)
* Service: unspecified

**Comment by EisenbergEffect** [comment]
That's good feedback. There was some debate ongoing higher up about how to handle support, so it might be slightly contentious. @ShevaDas would be great to follow up on this idea.

**Comment by mattwojo** [comment]
Thanks Rob. The feedback system looks great so far! :)

@ShevaDas Re: support -- we can show LOTS of evidence that our audience will be on these pages seeking support and that it will be reflected in the comments -- so some solution will be much better than no solution. Not offering any direction on where to seek support leaves both the customer and the internal writers and product owners frustrated with no clear expectation of what to do with the individualized support issues that will inevitably arise. Pointing to support.microsoft.com at least offers a solution even if it is replaced by something better in the future. The site offers lots of options for meeting the best support fit based on what a customer may be looking for. ¯\_(ツ)_/¯  Just my two cents.

**Comment by ShevaDas** [comment]
@mattwojo Thanks for the idea! I'll bring it up.

**Comment by ShevaDas** [comment]
@mattwojo Since the banner is transient, have you considered adding a link to the support site in the Resources section of the TOC?

**Comment by mattwojo** [comment]
@ShevaDas - I don't really 'own' any one particular content set, but work with many Windows partners to help them get their docs content on docs.ms. Many of them do have support info integrated somewhere in their content, though it is inconsistent.  The thing that appealed to me about integrating a support link into the new feedback mechanism is the consistency it provides.  I also am suggesting it as a direct response to the amount of Livefyre comments we received that fell into the category of individual support and seemed to be more appropriately directed to support.microsoft.com.  I understand the challenges that not everyone may want to direct their support to that URL as well, but wondering if that may be a bigger picture question to address re: why support.microsoft would not be the one-stop-shop for support that docs is aimed to be for documentation.
