### ISSUE TITLE
A1 is not how steak is done

### ISSUE THREAD

**Issue by jdanyow** [MicrosoftDocs/SamplesPages#8]
discuss...

[http://localhost:3000/en-us/devsandbox/conceptual/tabbed-conceptual](http://localhost:3000/en-us/devsandbox/conceptual/tabbed-conceptual)
Document ID: L2VuLXVzL2RldnNhbmRib3gvY29uY2VwdHVhbC90YWJiZWQtY29uY2VwdHVhbA==

**Comment by EisenbergEffect** [comment]
Good steak only requires salt, pepper and a hot grill or pan. If you want to get fancy, add some butter or make a wine sauce. Just say no to A1 ;)
